### PR TITLE
Penis-ify

### PR DESCRIPTION
**Pull request by MehTheTroll**
Signed off by: Kuttek Bhalla(tkar) <penis@penisdev.mcbc>

### CODE REVIEW

**Comment by rajasdate** [comment]
Bhalla sur making gerrit.. Push to penisos gerrit..

**Comment by rajasdate** [comment]
LMAO😂😂😂😂😂

**Comment by MehTheTroll** [comment]
OKAY SURR!
gayrit.penisless.mcbc

**Comment by darshan1205** [comment]
Thanks for your contributions to PhenexOS.

**Pull request closed without merging**
